# procurement_data_config.py
### This is where data configuration is stored for clean and maintainable code
### Scenario is procurement of Educational Materials for Grade 10 Science Class


import pandas as pd
import json
import os

# Path to the JSON file generated by scraper.py
JSON_FILE = "data/item_average_prices.json"

def load_prices_from_json(json_file):
    prices = {}
    if not os.path.exists(json_file):
        print(f"JSON file {json_file} not found. Please run scraper.py first.")
        return prices
    
    with open(json_file, mode="r", encoding="utf-8") as file:
        data = json.load(file)
        for item, details in data.items():
            prices[item] = details.get("avg_price", 0.0)
    return prices

# Load prices from JSON at module level
AVERAGE_PRICES = load_prices_from_json(JSON_FILE)

### PROCUREMENT_METHODS HERE ###

METHODS_DATA = {
    "Competitive Bidding": {
        "frequency": 0.5,
        "items": {item: AVERAGE_PRICES.get(item, 0.0) for item in [
            "Compound Microscope (1000x)", "Beaker 50ml", "Beaker 100ml", "Beaker 250ml", "Test Tube 15ml", 
            "Bunsen Burner", "Thermometer (-10 to 110C)", "Microscope Slides", "Lab Manual - Grade 10 Science", 
            "Erlenmeyer Flask 250ml", "Test Tube Rack", "Filter Paper pack of 100"]
        }
    },
    "Limited Source Bidding": {
        "frequency": 0.2,
        "items": {item: AVERAGE_PRICES.get(item, 0.0) for item in [
            "Refracting Telescope 70mm", "Triple Beam Balance", "pH Meter basic", "Graduated Cylinder 100ml", 
            "Hot Plate basic", "Stopwatch digital", "Prism glass", "Spring Scale 500g", "Bar Magnet pair", 
            "Tuning Fork 256 Hz", "Lens Set convex concave", "Ammeter basic"]
        }
    },
    "Negotiated Procurement": {
        "frequency": 0.2,
        "items": {item: AVERAGE_PRICES.get(item, 0.0) for item in [
            "Voltmeter basic", "Hydrochloric Acid Science Laboratory", "Dissecting Kit", "Petri Dishes pack of 20", 
            "Universal Indicator Solution 100ml", "Copper Sulfate", "Laboratory Rubber Stoppers", "Dropper Bottle 50ml", 
            "Laboratory Agar Powder 100g", "Iron Filings 250g"]
        }
    },
    "Direct Contracting": {
        "frequency": 0.1,
        "items": {item: AVERAGE_PRICES.get(item, 0.0) for item in [
            "Laboratory Safety Goggles", "Litmus Paper", "Pipette 10ml", "Laboratory Gloves nitrile box of 100", 
            "Laboratory Aprons pack of 10", "Funnel plastic 100mm", "Laboratory Alcohol Burner", "Fire Blanket", 
            "Test Tube Brush", "Microscope Coverslips box of 100", "Laboratory Spatula stainless steel"]
        }
    }
}

# Converting this into a DataFrame for manageable data handling
rows = []
for method, values in METHODS_DATA.items():
    frequency = values['frequency']
    items = values['items']

    for item, base_price in items.items():
        row = {
            "Method": method,
            "Frequency": frequency,
            "Item_Name": item,
            "Base_Price": base_price
        }
        rows.append(row)

### Final Procurement Data HERE

PROCUREMENT_DATA = pd.DataFrame(rows)

PROCUREMENT_OFFICERS = [
    'Casey Hernandez', 'Alex Rivera', 'James Patrick Mendoza', 'Morgan Cruz', 'Angela Ramirez', 
    'Taylor Martinez', 'Sophia Christine Navarro', 'Angela Renee Mendoza', 'Luke Andrew Navarro', 
    'Jamie Thompson', 'Christine Bautista'
]

### VOLATILITY VARIABLES (adjust for overall price fluctuation)
VOLATILITY_LOW = 0.05
VOLATILITY_MEDIUM = 0.10
VOLATILITY_HIGH = 0.15

BASE_PRICES = {
        "Compound Microscope (1000x)": 121409.38,
        "Refracting Telescope (70mm)": 5207.81,
        "Beaker (50ml)": 161.00,
        "Beaker (100ml)": 182.00,
        "Beaker (250ml)": 238.00,
        "Beaker (500ml)": 375.00,
        "Test Tube (10ml)": 19.00,
        "Test Tube (20ml)": 25.00,
        "Bunsen Burner": 334.62,
        "Triple Beam Balance": 2989.00,
        "Microscope Slides (box of 50)": 489.01,
        "Microscope Coverslips (box of 100)": 7520.34,
        "Dissecting Kit (basic)": 630.79,
        "Sodium Chloride (NaCl) - Solid (1kg)": 2700,
        "Hydrochloric Acid (HCl) - 1M (1L)": 1475.13,
        "Lab Manual - Grade 10 Science": 333.30,
        "Reflecting Telescope (150mm)": 20255.87,
        "Digital Spectrophotometer": 18519.60,
        "High-Precision Balance": 15915,
        "Potassium Iodide (KI) - Solid (500g)": 1661,
        "AmScope M150B-LED Replacement LED Bulb": 693.93,
        "Beaker (1000ml)": 2044,
        "Replacement Xenon Flash Lamp for Do PerkinElmer": 2893.78,
        "Sulfuric Acid (H2SO4) - 1M (1L)": 1302
}

ITEMS = list(BASE_PRICES.keys())

''' WE NEED TO PUT THIS IN PROCUREMENT_DATA.PY
    procurement_methods = {
    "Competitive Bidding": {
        "items": ["Compound Microscope (1000x)", "Refracting Telescope (70mm)", "Beaker (50ml)", "Beaker (100ml)", "Beaker (250ml)", "Beaker (500ml)", "Test Tube (10ml)", "Test Tube (20ml)", "Bunsen Burner", "Triple Beam Balance", "Microscope Slides (box of 50)", "Microscope Coverslips (box of 100)", "Dissecting Kit (basic)", "Sodium Chloride (NaCl) - Solid (1kg)", "Hydrochloric Acid (HCl) - 1M (1L)", "Lab Manual - Grade 10 Science"],
        "frequency": 0.5
    },
    "Limited Source Bidding": {
        "items": ["Reflecting Telescope (150mm)", "Digital Spectrophotometer", "Data Analysis Software (Logger Pro)", "High-Precision Balance"],
        "frequency": 0.2
    },
    "Negotiated Procurement": {
        "items": ["Potassium Iodide (KI) - Solid (500g)", "AmScope M150B-LED Replacement LED Bulb", "Beaker (1000ml)"],
        "frequency": 0.2
    },
    "Direct Contracting": {
        "items": ['Calibration Service (for high-precision balance)', "Replacement Xenon Flash Lamp for Do PerkinElmer", "Sulfuric Acid (H2SO4) - 1M (1L)"], 
        "frequency": 0.1
    }
    }
'''