# Generated by Django 5.2 on 2025-04-07 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0002_transaction_average_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainTransactionData",
            fields=[
                (
                    "block_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "block_number",
                    models.IntegerField(
                        db_index=True,
                        help_text="Sequential block number (index).",
                        unique=True,
                    ),
                ),
                ("previous_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "transaction_data_json",
                    models.JSONField(
                        help_text="The transaction data exactly as it was hashed (JSON format)."
                    ),
                ),
                (
                    "transaction_id_query",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "item_name_query",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "supplier_query",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "transaction_date_query",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "procurement_method_query",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Blockchain Record",
                "verbose_name_plural": "Blockchain Records",
                "ordering": ["block_number"],
            },
        ),
    ]
